FROM ubuntu:bionic-20210325

ENV PATH /usr/share/bcc/tools:$PATH
RUN sed -i "s#deb http://deb.debian.org/debian buster main#deb http://deb.debian.org/debian buster main contrib non-free#g" /etc/apt/sources.list

RUN apt-get update && apt-get install -y \
    ca-certificates \
    clang \
    curl \
    gcc \
    git \
    g++ \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

# Install dependencies for libbcc
# FROM: https://github.com/iovisor/bcc/blob/master/INSTALL.md#install-build-dependencies
RUN apt-get update && apt-get install -y \
    debhelper \
    cmake \
    libllvm3.9 \
    llvm-dev \
    libclang-dev \
    libelf-dev \
    bison \
    flex \
    libedit-dev \
    clang-format \
    python \
    python3-pyroute2 \
    luajit \
    libluajit-5.1-dev \
    arping \
    iperf \
    ethtool \
    devscripts \
    zlib1g-dev \
    libfl-dev \
    --no-install-recommends \
    && rm -rf /var/lib/apt/lists/*

ENV BCC_VERSION v0.20.0

RUN git clone --depth 1 --branch "$BCC_VERSION" https://github.com/iovisor/bcc.git /usr/src/bcc \
	&& ( \
		cd /usr/src/bcc \
		&& mkdir build \
		&& cd build \
		&& cmake .. -DCMAKE_INSTALL_PREFIX=/usr \
		&& make \
		&& make install \
	) \
	&& rm -rf /usr/src/bcc

RUN mkdir /work
WORKDIR /work

RUN git clone --depth 1 https://github.com/brendangregg/FlameGraph
  
ENTRYPOINT ["/bin/bash"]
