FROM microsoft/dotnet:2.2-runtime-deps-stretch-slim

RUN apt-get update \
    && apt-get install -y --no-install-recommends \
        curl \
    && rm -rf /var/lib/apt/lists/*

# Install .NET Core
ENV DOTNET_VERSION 2.2.0-preview3-27014-02

RUN curl -SL --output dotnet.tar.gz https://dotnetcli.blob.core.windows.net/dotnet/Runtime/$DOTNET_VERSION/dotnet-runtime-$DOTNET_VERSION-linux-x64.tar.gz \
    && dotnet_sha512='63bee8876ca3166f81a14f95aebaa84a91da94fcaf1b33328594cf68bb0f43db75ed56d1afbf9b89d375b535f3ec0d938ac56b6c18d790d5a5b6bfd4e36782b7' \
    && echo "$dotnet_sha512 dotnet.tar.gz" | sha512sum -c - \
    && mkdir -p /usr/share/dotnet \
    && tar -zxf dotnet.tar.gz -C /usr/share/dotnet \
    && rm dotnet.tar.gz \
    && ln -s /usr/share/dotnet/dotnet /usr/bin/dotnet

RUN apt-get update && apt-get install -y wget \
    libgtk-3-0 \
    libxss1 \
    libgconf-2-4 \
    libnss3 \
    libgnome-keyring0 \
    libasound2

RUN mkdir -p /temp/install && \
    wget -q https://download.microsoft.com/download/A/E/3/AE32C485-B62B-4437-92F7-8B6B2C48CB40/StorageExplorer-linux-x64.tar.gz -O storageexplorer.tar.gz && \
    tar -xvf storageexplorer.tar.gz && ls -l

ENTRYPOINT ./StorageExplorer --disable-gpu