#docker run -it --rm --net host -v /tmp/.X11-unix:/tmp/.X11-unix -e DISPLAY=unix$DISPLAY --device /dev/video0:/dev/video0 -v /dev/bus/:/dev/bus/ --device /dev/dri --ipc=host -v /dev/shm:/dev/shm aimvector/airtame
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y curl

RUN mkdir /airtame && cd airtame && curl -sSL http://downloads-cdn.airtame.com/application/ga/lin_x64/releases/airtame-application-3.3.2.tar.gz -o airtame.tar.gz

RUN apt-get install -y sudo libgtk2.0-0 libx11-xcb1 libxtst6 libxss1 
RUN apt-get install -y ca-certificates libgconf-2-4 libnss3
RUN apt-get install -y libasound2
RUN apt-get install -y wget
RUN apt-get install -y nano
RUN apt-get install -y libgstreamer1.0-0 gstreamer1.0-plugins-base gstreamer1.0-plugins-good gstreamer1.0-plugins-bad gstreamer1.0-plugins-ugly gstreamer1.0-libav gstreamer1.0-doc gstreamer1.0-tools gstreamer1.0-x gstreamer1.0-alsa gstreamer1.0-gl gstreamer1.0-gtk3 gstreamer1.0-qt5 gstreamer1.0-pulseaudio
RUN cd /airtame && \
    tar -xzf airtame.tar.gz && \
    cd airtame-application-3.3.2 && \
    ls -l && \
    chmod +x install.sh && \
    ./install.sh

WORKDIR airtame/airtame-application-3.3.2/

ENV LD_LIBRARY_PATH=resources/deps/airtame-core/lib:resources/deps/airtame-encryption/lib 

CMD ./airtame-application --disable-gpu --enable-transparent-visuals

#ENTRYPOINT /bin/bash
