FROM aimvector/linux as build

ARG LINUX_KERNEL_VERSION

RUN git checkout $LINUX_KERNEL_VERSION && \
    cd tools/perf && ls -l && make O=/tmp/ && ls /tmp/

RUN rm -rf /src
WORKDIR /tmp
################################################################################################################
FROM ubuntu:18.04

RUN apt-get update && apt-get install -y libelf-dev libdw-dev libaudit-dev

COPY --from=build /tmp/ /perf/
WORKDIR /out

ENTRYPOINT ["/perf/perf"]
