FROM debian:bookworm-slim

RUN apt-get update && apt-get install -y wget
RUN wget -q https://packages.mozilla.org/apt/repo-signing-key.gpg -O- | tee /etc/apt/keyrings/packages.mozilla.org.asc > /dev/null
RUN echo "deb [signed-by=/etc/apt/keyrings/packages.mozilla.org.asc] https://packages.mozilla.org/apt mozilla main" | tee -a /etc/apt/sources.list.d/mozilla.list > /dev/null
RUN echo ' \n\
	Package: * \n\
	Pin: origin packages.mozilla.org \n\
	Pin-Priority: 1000 \n\
	' | tee /etc/apt/preferences.d/mozilla

RUN apt-get update && apt-get install -y firefox

ENTRYPOINT [ "/usr/bin/firefox" ]