FROM alpine:3.9
RUN apk -v --update add \
        python \
        py-pip \
        groff \
        less \
        bash \
        mailcap \
        && \
    pip install --upgrade awscli==1.16.204 s3cmd==2.0.1 python-magic && \
    apk -v --purge del py-pip && \
    rm /var/cache/apk/*
VOLUME /root/.aws
VOLUME /project
WORKDIR /project
CMD /bin/bash