FROM debian:jessie

ENV MONO_VERSION 5.12.0.226

#TOOLS
RUN apt-get update \
  && apt-get install -y curl unzip lsof \
  && rm -rf /var/lib/apt/lists/*

#LIBS
RUN apt-get update && apt-get install -y libgtk2.0-0 \
  libcanberra-gtk-module \
  libglib2.0-bin \
  libglib2.0-0 \
  gsettings-desktop-schemas \
  && rm -rf /var/lib/apt/lists/*

#MONO
RUN apt-key adv --keyserver hkp://keyserver.ubuntu.com:80 --recv-keys 3FA7E0328081BFF6A14DA29AA6A19B38D3D831EF
RUN echo "deb http://download.mono-project.com/repo/debian stable-jessie/snapshots/$MONO_VERSION main" > /etc/apt/sources.list.d/mono-official-stable.list \
  && apt-get update \
  && apt-get install -y mono-complete \
  && rm -rf /var/lib/apt/lists/* /tmp/*

#FIDDLER
RUN mkdir -p /Fiddler && \
    cd /Fiddler && \
    curl -O http://telerik-fiddler.s3.amazonaws.com/fiddler/fiddler-linux.zip && \
    unzip fiddler-linux.zip && rm fiddler-linux.zip
    
WORKDIR /Fiddler

ENTRYPOINT ["mono", "Fiddler.exe"]